trigger:
- master

variables:
  dockerRegistryServiceConnection: '42d8d133-6860-4cf5-90f6-ed37475d90cd'
  imageRepository: 'imgapitodo'
  containerRegistry: 'apitodo.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  displayName: Download appsettings.json
  name: appsettings
  inputs:
    secureFile: 'appsettings.Production.json'
    
- script: |
    mkdir /app
    chmod +x /app
    cp $(appsettings.secureFilePath) /app

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)
